-- CREATE EXTENSIONS

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "citext";


-- CREATE ENUMS

CREATE TYPE channel_type AS ENUM ('DM', 'GROUP');
CREATE TYPE message_type AS ENUM ('TEXT', 'IMAGE', 'VIDEO', 'FILE', 'SYSTEM');
CREATE TYPE participation_status AS ENUM ('INVITED', 'JOINED', 'LEFT', 'BANNED');

CREATE TYPE participants_role AS ENUM ('OWNER', 'ADMIN', 'MEMBER');
CREATE TYPE reaction_type AS ENUM ('LIKE', 'LOVE', 'HAHA', 'WOW', 'SAD', 'ANGRY');
CREATE TYPE user_status AS ENUM ('ONLINE', 'OFFLINE', 'AWAY', 'DO_NOT_DISTURB');

CREATE TYPE role_type AS ENUM ('ADMIN', "USER");
CREATE TYPE notification_type AS ENUM ('MENTION', 'REPLY', 'REACTION', 'FOLLOW', 'MESSAGE');
CREATE TYPE ev

-- CREATE TABLES

